server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlite:revado.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true